version: '1.0'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URI=postgresql://postgres:password123@host.docker.internal/hobbyto
      - JWT_SECRET=ThatGuyDerrickDances101202303444555
      - REDIS_URL=redis://redis:6379/0
      - FLASK_ENV=development
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
