version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app/backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URI=postgresql://postgres:password123@host.docker.internal/hobbyto
      - JWT_SECRET=ThatGuyDerrickDances101202303444555
      - REDIS_URL=redis://redis:6379/0
      - FLASK_ENV=development
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app/frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
